### ISSUE TITLE
error: argument of type "cublasStatus_t" is incompatible with parameter of type "cudaError_t"

### ISSUE THREAD

**Issue by ding-ding2000** [CalvinXKY/BasicCUDA#4]
![image](https://github.com/user-attachments/assets/71221f04-562e-4302-9c95-b30b56bd095c)
Is this a problem with the cuda version?My cuda version is 11.7.

**Comment by CalvinXKY** [comment]
@ding-ding2000  Yes, this issue arises when the version is higher. Simply removing the check for the cuBLAS function will allow it to run normally. I feel I need to fix this issue.
